//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.27 at 12:13:25 PM CET 
//


package no.arkivverket.helsearkiv.nhareg.domene.avleveringsdokumentasjon;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * En instans av denne klassen benyttes for å registrere opplysninger om en avtale om avlevering av materiale fra et
 * pasientarkiv som er inngått mellom arkivskaper og arkivdepot.
 *
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="avleveringsidentifikator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="arkivskaper_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="arkiv_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="avtaledato" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dato_for_pasientutvelgelse" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="planlagt_oppstart" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="planlagt_avsluttet" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="utfyllende_opplysninger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "avleveringsidentifikator",
    "arkivskaperID",
    "arkivID",
    "avtaledato",
    "datoForPasientutvelgelse",
    "planlagtOppstart",
    "planlagtAvsluttet",
    "utfyllendeOpplysninger"
})
@XmlRootElement(name = "Avleveringsbeskrivelse")
public class Avleveringsbeskrivelse
    implements Serializable
{

    @XmlElement(required = true)
    protected String avleveringsidentifikator;
    @XmlElement(name = "arkivskaper_ID", required = true)
    protected String arkivskaperID;
    @XmlElement(name = "arkiv_ID", required = true)
    protected String arkivID;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar avtaledato;
    @XmlElement(name = "dato_for_pasientutvelgelse", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar datoForPasientutvelgelse;
    @XmlElement(name = "planlagt_oppstart", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar planlagtOppstart;
    @XmlElement(name = "planlagt_avsluttet", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar planlagtAvsluttet;
    @XmlElement(name = "utfyllende_opplysninger")
    protected String utfyllendeOpplysninger;

    /**
     * Gets the value of the avleveringsidentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvleveringsidentifikator() {
        return avleveringsidentifikator;
    }

    /**
     * Sets the value of the avleveringsidentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvleveringsidentifikator(String value) {
        this.avleveringsidentifikator = value;
    }

    /**
     * Gets the value of the arkivskaperID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArkivskaperID() {
        return arkivskaperID;
    }

    /**
     * Sets the value of the arkivskaperID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArkivskaperID(String value) {
        this.arkivskaperID = value;
    }

    /**
     * Gets the value of the arkivID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArkivID() {
        return arkivID;
    }

    /**
     * Sets the value of the arkivID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArkivID(String value) {
        this.arkivID = value;
    }

    /**
     * Gets the value of the avtaledato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getAvtaledato() {
        return avtaledato;
    }

    /**
     * Sets the value of the avtaledato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvtaledato(Calendar value) {
        this.avtaledato = value;
    }

    /**
     * Gets the value of the datoForPasientutvelgelse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDatoForPasientutvelgelse() {
        return datoForPasientutvelgelse;
    }

    /**
     * Sets the value of the datoForPasientutvelgelse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoForPasientutvelgelse(Calendar value) {
        this.datoForPasientutvelgelse = value;
    }

    /**
     * Gets the value of the planlagtOppstart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getPlanlagtOppstart() {
        return planlagtOppstart;
    }

    /**
     * Sets the value of the planlagtOppstart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanlagtOppstart(Calendar value) {
        this.planlagtOppstart = value;
    }

    /**
     * Gets the value of the planlagtAvsluttet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getPlanlagtAvsluttet() {
        return planlagtAvsluttet;
    }

    /**
     * Sets the value of the planlagtAvsluttet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanlagtAvsluttet(Calendar value) {
        this.planlagtAvsluttet = value;
    }

    /**
     * Gets the value of the utfyllendeOpplysninger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtfyllendeOpplysninger() {
        return utfyllendeOpplysninger;
    }

    /**
     * Sets the value of the utfyllendeOpplysninger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtfyllendeOpplysninger(String value) {
        this.utfyllendeOpplysninger = value;
    }

}
