//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.27 at 12:13:25 PM CET 
//


package no.arkivverket.helsearkiv.nhareg.domene.avleveringsdokumentasjon;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.arkivverket.helsearkiv.nhareg.domene.avleveringsdokumentasjon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.arkivverket.helsearkiv.nhareg.domene.avleveringsdokumentasjon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Avleveringsbeskrivelse }
     * 
     */
    public Avleveringsbeskrivelse createAvleveringsbeskrivelse() {
        return new Avleveringsbeskrivelse();
    }

    /**
     * Create an instance of {@link OverførtTilNyAvlevering }
     * 
     */
    public OverførtTilNyAvlevering createOverførtTilNyAvlevering() {
        return new OverførtTilNyAvlevering();
    }

    /**
     * Create an instance of {@link OverføringTilArkivdepot }
     * 
     */
    public OverføringTilArkivdepot createOverføringTilArkivdepot() {
        return new OverføringTilArkivdepot();
    }

    /**
     * Create an instance of {@link Avleveringsoversikt }
     * 
     */
    public Avleveringsoversikt createAvleveringsoversikt() {
        return new Avleveringsoversikt();
    }

    /**
     * Create an instance of {@link Oppdateringsinfo }
     * 
     */
    public Oppdateringsinfo createOppdateringsinfo() {
        return new Oppdateringsinfo();
    }

    /**
     * Create an instance of {@link Avleveringsdokumentasjon }
     * 
     */
    public Avleveringsdokumentasjon createAvleveringsdokumentasjon() {
        return new Avleveringsdokumentasjon();
    }

}
