//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.27 at 12:13:25 PM CET 
//


package no.arkivverket.helsearkiv.nhareg.domene.avleveringsdokumentasjon;

import lombok.Data;
import no.arkivverket.helsearkiv.nhareg.domene.adapter.StringDateTimeAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.Calendar;


/**
 * En instans av denne klassen benyttes for å registrere opplysninger om oppdatering av avleveringsbeskrivelsen.
 */
@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sistOppdatert",
    "oppdatertAv",
    "prosesstrinn"
})
@XmlRootElement(name = "Oppdateringsinfo")
public class Oppdateringsinfo implements Serializable {

    @XmlElement(name = "sist_oppdatert", required = true, type = String.class)
    @XmlJavaTypeAdapter(StringDateTimeAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar sistOppdatert;
    
    @XmlElement(name = "oppdatert_av", required = true)
    protected String oppdatertAv;
    
    @XmlElement(required = true)
    protected String prosesstrinn;

}
