//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.27 at 12:13:25 PM CET 
//


package no.arkivverket.helsearkiv.nhareg.domene.avleveringsdokumentasjon;

import no.arkivverket.helsearkiv.nhareg.domene.adapter.StringDateAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.Calendar;


/**
 * 
 *                     Dersom avleveringsuttrekket for en pasient ikke blir godtatt av arkivdepotet, skal pasienten overføres til en ny avlevering. Dette skal registreres i en instans av denne klassen.
 *                 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dato_overført_til_ny_avleveringsoversikt" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ny_avleveringsidentifikator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datoOverf\u00f8rtTilNyAvleveringsoversikt",
    "nyAvleveringsidentifikator"
})
@XmlRootElement(name = "Overf\u00f8rt_til_ny_avlevering")
public class OverførtTilNyAvlevering
    implements Serializable
{

    @XmlElement(name = "dato_overf\u00f8rt_til_ny_avleveringsoversikt", required = true, type = String.class)
    @XmlJavaTypeAdapter(StringDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected Calendar datoOverførtTilNyAvleveringsoversikt;
    @XmlElement(name = "ny_avleveringsidentifikator", required = true)
    protected String nyAvleveringsidentifikator;

    /**
     * Gets the value of the datoOverførtTilNyAvleveringsoversikt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getDatoOverførtTilNyAvleveringsoversikt() {
        return datoOverførtTilNyAvleveringsoversikt;
    }

    /**
     * Sets the value of the datoOverførtTilNyAvleveringsoversikt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatoOverførtTilNyAvleveringsoversikt(Calendar value) {
        this.datoOverførtTilNyAvleveringsoversikt = value;
    }

    /**
     * Gets the value of the nyAvleveringsidentifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNyAvleveringsidentifikator() {
        return nyAvleveringsidentifikator;
    }

    /**
     * Sets the value of the nyAvleveringsidentifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNyAvleveringsidentifikator(String value) {
        this.nyAvleveringsidentifikator = value;
    }

}
